# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')])),
                ('sentence', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('timer', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSynom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=150)),
                ('synonyms', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneSynom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=150)),
                ('synonyms', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[(None, 'SELECT'), ('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=6, null=True)),
                ('gene', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('aas', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, choices=[(None, 'SELECT'), ('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III'), ('Stage IV', 'Stage IV'), ('Stage X', 'Stage X'), ('Stage IA', 'Stage IA'), ('Stage IIA', 'Stage IIA'), ('Stage IIIA', 'Stage IIIA'), ('Stage IVA', 'Stage IVA'), ('Stage IB', 'Stage IB'), ('Stage IIB', 'Stage IIB'), ('Stage IIIB', 'Stage IIIB'), ('Stage IVB', 'Stage IVB'), ('Stage IC', 'Stage IC'), ('Stage IIC', 'Stage IIC'), ('Stage IIIC', 'Stage IIIC'), ('Stage IVC', 'Stage IVC')], max_length=10, null=True)),
                ('grade', models.CharField(blank=True, choices=[(None, 'SELECT'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade I', 'Grade I'), ('Grade II', 'Grade II'), ('Grade III', 'Grade III'), ('Grade IV', 'Grade IV')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology', models.BooleanField(default=False)),
                ('withoutAAS', models.BooleanField(default=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Index')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Query')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct', models.CharField(max_length=20)),
                ('disease', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('gene', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('aas', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Query'),
        ),
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.ManyToManyField(to='validation.Section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Trial'),
        ),
    ]
