# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='query',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='section',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='index',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='query',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='scenario',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
