# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20161004_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')])),
                ('sentence', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('timer', models.IntegerField(blank=True, default=None, null=True)),
                ('section', models.ManyToManyField(to='validation.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology', models.BooleanField(default=False)),
                ('withoutAAS', models.BooleanField(default=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Index')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct', models.CharField(max_length=20)),
                ('disease', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('gene', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('aas', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Query')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Trial'),
        ),
    ]
