# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20161004_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='disease',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
