# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diff_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField()),
                ('after', models.TextField()),
                ('caseName', models.CharField(default='diff tool case', max_length=200)),
            ],
        ),
    ]
